# Generated by Django 4.1.7 on 2025-01-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0002_alter_telegramuser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video", models.FileField(upload_to="videos/")),
            ],
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
