# Generated by Django 5.1.5 on 2025-01-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0003_video_telegramuser_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="balance",
            field=models.FloatField(default=0),
        ),
    ]
