# Generated by Django 5.1.5 on 2025-01-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0004_alter_telegramuser_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="can_watch",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="last_time_wathed",
            field=models.FloatField(default=1737583637.221907),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="watched_videos",
            field=models.IntegerField(default=0),
        ),
    ]
