from .main_menu_kb import main_menu_kb
from .oznakomlen_kb import oznakomlen_kb
from .prosmotreno import prosmotreno_kb
from .tarrifs_n_withdraw import tarrifs_n_withdraw
from .oformit_individual import oformit_individual
from .payment_metod import payment_method
from .add_method import add_method
from .choose_tariff import choose_tariff    
from .cancel import cancel